#
# Buitenverlichting
#
# Uit
- id: '1'
  alias: '[Tuin] - Buitenverlichting uit'
  trigger:
  - platform: numeric_state
    entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
    above: 100
    for:
      minutes: 3
  action:
  - service: switch.turn_off
    data:
      entity_id: group.buitenverlichting
  - service: switch.turn_off
    data:
      entity_id: group.tuinverlichting
# Aan
- id: '2'
  alias: '[Tuin] - Buitenverlichting aan'
  trigger:
  - platform: numeric_state
    entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
    below: 50
    for:
      minutes: 3
  action:
  - service: switch.turn_on
    data:
      entity_id: group.buitenverlichting
  - service: switch.turn_on
    data:
      entity_id: group.tuinverlichting
#
# Binnenverlichting
# 
# Uit
- id: '3'
  alias: '[Woonkamer] - Woonkamerverlichting uit'
  trigger:
  - platform: numeric_state
    entity_id: sensor.gemiddeld_lichtniveau
    above: 200
    for:
      minutes: 3
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_off
    data:
      entity_id:  
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.smart_plug_plant_lamp_switch_3
# Aan
- id: '4'
  alias: '[Woonkamer] - Woonkamer lampen aan'
  trigger:
  - platform: numeric_state
    entity_id: sensor.gemiddeld_lichtniveau
    below: 150
    for:
      minutes: 3
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: state
      entity_id: input_boolean.afstandbediening
      # Als deze input_boolean 'on' is, is de afstandbediening gebruikt om de lampen uit te zetten
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
      color_temp: 443
      brightness: 200
  - service: light.turn_on
    data:
      entity_id: light.hal_plafond
      color_temp: 443
      brightness: 65
  - service: homeassistant.turn_on
    data:
      entity_id:   
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.smart_plug_plant_lamp_switch_3
# Uit in de nacht
- id: '5'
  alias: '[Woonkamer] - Woonkamerverlichting uit in de nacht'
  trigger:
  - platform: time
    at: '22:30:00'
  condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: timer.woonkamer
        state: idle
      - condition: template
        value_template: >
          {{ states.remote.harmony_hub_2.attributes["current_activity"] == "PowerOff" }}
      - condition: or
        conditions:
        - condition: state
          entity_id: light.woonkamer
          state: 'on'
        - condition: state
          entity_id: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
          state: 'on'
        - condition: state
          entity_id: switch.smart_plug_plant_lamp_switch_3
          state: 'on'
  action:
  - delay: >
      {{ (range(0, 2)|random|int) }}:{{ (range(1, 59)|random|int) }}:00
  - service: light.turn_off
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_off
    data:
      entity_id:   
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.smart_plug_plant_lamp_switch_3
#
# Afstandbediening
#
- id: '6'
  alias: '[Remote] - Afstandbediening gebruikt'
  trigger:
  - platform: state
    entity_id: sensor.afstandbediening_woonkamer
  condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.state != trigger.from_state.state }}
  action:
  - entity_id: input_boolean.afstandbediening
# hue/woonkamer_schakelaar/buttonevent 1002 Aan
# hue/woonkamer_schakelaar/buttonevent 2002 Feller
# hue/woonkamer_schakelaar/buttonevent 3002 Dimmen
# hue/woonkamer_schakelaar/buttonevent 4002 Uit
    service_template: >
      {% if states('sensor.afstandbediening_woonkamer')|int == 4002 %}
        homeassistant.turn_on 
      {% else %} 
        homeassistant.turn_off 
      {% endif %}
#  - service: input_select.select_option
#    data_template:
#      entity_id: input_boolean.afstandbediening
#      option: >
#        {% if states('sensor.afstandbediening_woonkamer')|int == 4002 %}
#          homeassistant.turn_on 
#        {% else %} 
#          homeassistant.turn_off 
#        {% endif %}
# Afstandbediening reset
- id: '7'
  alias: '[Remote] - Afstandbediening reset'
  trigger:
  - platform: numeric_state
    entity_id: sensor.gemiddeld_lichtniveau
    above: 400
  - platform: time
    at: '12:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.afstandbediening
# Verlichting uit door afstandbediening
- id: '8'
  alias: '[Woonkamer] - Schakel Zwave woonkamer verlichting uit'
  trigger:
  - entity_id: sensor.afstandbediening_woonkamer
    platform: state
    to: '4002'
  action:
  - service: homeassistant.turn_off
    entity_id:  
    - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
    - switch.smart_plug_plant_lamp_switch_3
# Verlichting aan door afstandbediening
- id: '9'
  alias: '[Woonkamer] - Schakel Zwave woonkamer verlichting aan'
  trigger:
  - entity_id: sensor.afstandbediening_woonkamer
    platform: state
    to: '1002'
  action:
  - service: homeassistant.turn_on
    entity_id:  
    - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
    - switch.smart_plug_plant_lamp_switch_3
#
# Tuinverlichting uit
# 
- id: '10'
  alias: '[Tuin] - Tuinverlichting uit in de nacht'
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: group.tuinverlichting
    state: 'on'
  action:
  - delay: >
      {{ "00:%02d:00" % (range(5, 59) | random) }}
  - service: homeassistant.turn_off
    entity_id: group.tuinverlichting
#
# Regenachtige dag
#
- id: '11'
  alias: '[Weer] - Regenachtige dag monitor'
  trigger:
  - below: 120
    entity_id: sensor.gemiddeld_lichtniveau
    platform: numeric_state
  - above: 190
    entity_id: sensor.gemiddeld_lichtniveau
    platform: numeric_state
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    - condition: state
      entity_id: timer.regenachtigedag
      state: idle
    - condition: state
      entity_id: group.familie
      state: home
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.br_condition
        state: rainy
      - condition: state
        entity_id: sensor.br_condition
        state: snowy
  action:
  - data:
      entity_id: timer.regenachtigedag
    service: timer.start
  - entity_id: input_boolean.regenachtigedag
    service_template: >
      {% if states('sensor.gemiddeld_lichtniveau')|int < 125 %}
        homeassistant.turn_on 
      {% else %} 
        homeassistant.turn_off 
      {% endif %}
# Verlichting uit bij regenachtige dag
- id: '12'
  alias: '[Weer] - Regenachtige dag verlichting uit'
  trigger:
  - platform: state
    entity_id: input_boolean.regenachtigedag
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_off
    data:
      entity_id: 
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.smart_plug_plant_lamp_switch_3
# Verlichting aan bij regenachtige dag
- id: '13'
  alias: '[Weer] - Regenachtige dag verlichting aan'
  trigger:
  - platform: state
    entity_id: input_boolean.regenachtigedag
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_on
    data:
      entity_id: 
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.smart_plug_plant_lamp_switch_3
#
# Theming
#
# Dag licht theme
- id: '14'
  alias: '[Thema] - Light theme after Sunrise'
  trigger:
    - platform: sun
      event: sunrise
  action:
    - service: frontend.set_theme
      data:
        # Light theme bij start
        name: Google - Light
- id: '15'
  alias: '[Thema] - Dark theme after Sunset'
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: frontend.set_theme
      data:
        # Dark theme bij start
        name: Google - Dark
- id: '16'
  alias: '[Thema] - Light theme after reboot in day'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - service: frontend.set_theme
      data:
        # Light theme bij zonsopgang
        name: Google - Light
- id: '17'
  alias: '[Thema] - Dark theme after reboot in night'
  trigger:
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: frontend.set_theme
      data:
        # Dark theme bij zonsondergang
        name: Google - Dark
- id: '18'
  alias: '[Beweging] - Timer voor beweging in de woonkamer'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor, binary_sensor.woonkamer_sensor_motion
    to: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.woonkamer
#
# Deurbel
#
- id: '19'
  alias: '[Deurbel] - Verlichting knipperen bij aanbellen avond'
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_ding
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: group.woonkamer
    state: 'on'
  action:
  - service: homeassistant.toggle
    entity_id:
    - group.woonkamer
  - delay: 00:00:01
  #- service: homeassistant.toggle
  #  entity_id:
  #  - group.woonkamer
  #- delay: 00:00:01
  #- service: homeassistant.toggle
  #  entity_id:
  #  - group.woonkamer
  #- delay: 00:00:01
  - service: homeassistant.toggle
    entity_id:
    - group.woonkamer
  - delay: 00:00:07
- id: '20'
  alias: '[Keuken] - Dim keukenverlichting om 20u'
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: light.keuken
    state: 'on'
  action:
  - delay: >
      {{ "00:%02d:00" % (range(1, 5) | random) }}
  - service: light.turn_on
    data:
      entity_id:
      - light.keuken
      color_temp: 443
      brightness: 100
#
# Update notificatie
#
- id: '21'
  alias: '[Update] - Update Available Notification'
  trigger:
  - platform: state
    entity_id: sensor.majorupdateavailable
    to: 'true'
  condition:
  - condition: template
    value_template: >
      {{ states.sensor.installed_version.state.split(".")[1] != states.binary_sensor.updater.attributes.newest_version.split(".")[1] }}
  action:
  - service: notify.hass_notification
    data_template:
      title: "Home Assistant Major Update Notificatie"
      message: >
        Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available.
      data:
        url: "https://www.home-assistant.io/latest-release-notes/"
      target: device/GertjanOP3T

# Airconditioning
- id: '22'
  alias: '[Airco] - Zet airco overloop aan'
  trigger:
    - platform: numeric_state
      entity_id: sensor.gemiddelde_temperature_boven
      above: 24
  condition:
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.br_minimum_temperature_1d
        above: 18
      - condition: numeric_state
        entity_id: sensor.br_temperature
        above: 28
    - condition: state
      entity_id: input_boolean.vakantie_mode
      state: 'off'
  action:
    - service: climate.set_fan_mode
      data:
        entity_id: climate.overloop
        fan_mode: '5'
    - service: climate.set_temperature
      data:
        entity_id: climate.overloop
        temperature: 18
        hvac_mode: cool
    - service: climate.turn_on
      entity_id: climate.overloop
- id: '23'
  alias: '[Airco] - Zet airco zolder aan'
  trigger:
    - platform: template
      value_template: >
          {{ states.climate.overloop.attributes['current_temperature'] | round(1) > 24 }}
  condition:
    - condition: or
      conditions:
      - condition: numeric_state
        entity_id: sensor.br_minimum_temperature_1d
        above: 18
      - condition: numeric_state
        entity_id: sensor.br_temperature
        above: 28
    - condition: state
      entity_id: input_boolean.vakantie_mode
      state: 'off'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.zolder
        temperature: 18
        hvac_mode: cool
    - service: climate.set_fan_mode
      data:
        entity_id: climate.zolder
        fan_mode: 'Auto'
    - service: climate.set_swing_mode
      data:
        entity_id: climate.zolder
        swing_mode: '3D'
    - service: climate.turn_on
      entity_id: climate.overloop
- id: '24'
  alias: '[Airco] - Zet airco overloop uit'
  trigger:
    - platform: numeric_state
      entity_id: sensor.gemiddelde_temperature_boven
      below: 18
  action:
    - service: climate.turn_off
      entity_id: climate.zolder
- id: '25'
  alias: '[Airco] - Zet airco zolder uit'
  trigger:
    - platform: template
      value_template: >
          {{ states.climate.overloop.attributes['current_temperature'] | round(1) < 18 }}
  action:
    - service: climate.turn_off
      entity_id: climate.zolder
# Error notificatie
- id: '26'
  alias: '[Logging] - Error notificatie'
  trigger:
      platform: event
      event_type: system_log_event
      event_data:
        level: ERROR
  action:
    - service: notify.hass_notification
      data_template:
        title: "Error notificatie"
        message: >
          {{ trigger.event.data.message }}
        target:
        - device/GertjanOP3T