#
# Buitenverlichting
#
# Uit
- id: '1'
  alias: '[Garden] - Buitenverlichting uit'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
    above: 100
    for:
      minutes: 3
  action:
  - service: switch.turn_off
    data:
      entity_id: group.buitenverlichting
  - service: switch.turn_off
    data:
      entity_id: group.tuinverlichting
# Aan
- id: '2'
  alias: '[Garden] - Buitenverlichting aan'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
    below: 50
    for:
      minutes: 3
  action:
  - service: switch.turn_on
    data:
      entity_id: group.buitenverlichting
  - service: switch.turn_on
    data:
      entity_id: group.tuinverlichting
#
# Binnenverlichting
# 
# Uit
- id: '3'
  alias: '[Living] - Woonkamerverlichting uit'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.gemiddeld_lichtniveau
    above: 200
    for:
      minutes: 3
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_off
    data:
      entity_id:  
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
# Aan
- id: '4'
  alias: '[Living] - Woonkamer lampen aan'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.gemiddeld_lichtniveau
    below: 150
    for:
      minutes: 3
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.woonkamer
      state: 'off'
    - condition: state
      entity_id: input_boolean.afstandbediening
      # Als deze input_boolean 'on' is, is de afstandbediening gebruikt om de lampen uit te zetten
      state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
      color_temp: 443
      brightness: 200
  - service: homeassistant.turn_on
    data:
      entity_id:   
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
# Uit in de nacht
- id: '5'
  alias: '[Living] - Woonkamerverlichting uit in de nacht'
  initial_state: true
  trigger:
  - platform: time
    at: '22:30:00'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: timer.woonkamer
      state: idle
    - condition: state
      entity_id: light.woonkamer
      state: 'on'
    - condition: state
      entity_id: group.televisie_activiteit
      state: 'off'
  action:
  - delay: >
      {{ (range(0, 2)|random|int) }}:{{ (range(1, 59)|random|int) }}:00
  - service: light.turn_off
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_off
    data:
      entity_id:   
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
#
# Afstandbediening
#
- id: '6'
  alias: '[Remote] - Afstandbediening gebruikt'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.afstandbediening_woonkamer
  condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.state != trigger.from_state.state }}
  action:
  - entity_id: input_boolean.afstandbediening
# hue/woonkamer_schakelaar/buttonevent 1002 Aan
# hue/woonkamer_schakelaar/buttonevent 2002 Feller
# hue/woonkamer_schakelaar/buttonevent 3002 Dimmen
# hue/woonkamer_schakelaar/buttonevent 4002 Uit
    service_template: >
      {% if states('sensor.afstandbediening_woonkamer')|int == 4002 %}
        homeassistant.turn_on 
      {% else %} 
        homeassistant.turn_off 
      {% endif %}
#  - service: input_select.select_option
#    data_template:
#      entity_id: input_boolean.afstandbediening
#      option: >
#        {% if states('sensor.afstandbediening_woonkamer')|int == 4002 %}
#          homeassistant.turn_on 
#        {% else %} 
#          homeassistant.turn_off 
#        {% endif %}
# Afstandbediening reset
- id: '7'
  alias: '[Remote] - Afstandbediening reset'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.gemiddeld_lichtniveau
    above: 400
  - platform: time
    at: '12:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.afstandbediening
# Verlichting uit door afstandbediening
- id: '8'
  alias: '[Living] - Schakel Zwave woonkamer verlichting uit'
  initial_state: true
  trigger:
  - entity_id: sensor.afstandbediening_woonkamer
    platform: state
    to: '4002'
  action:
  - service: homeassistant.turn_off
    entity_id:  
    - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
    - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
# Verlichting aan door afstandbediening
- id: '9'
  alias: '[Living] - Schakel Zwave woonkamer verlichting aan'
  initial_state: true
  trigger:
  - entity_id: sensor.afstandbediening_woonkamer
    platform: state
    to: '1002'
  action:
  - service: homeassistant.turn_on
    entity_id:  
    - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
    - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
#
# Tuinverlichting uit
# 
- id: '10'
  alias: '[Garden] - Tuinverlichting uit in de nacht'
  initial_state: true
  trigger:
  - platform: time
    at: '23:00:00'
  condition:
  - condition: state
    entity_id: group.tuinverlichting
    state: 'on'
  action:
  - delay: >
      {{ "00:%02d:00" % (range(5, 59) | random) }}
  - service: homeassistant.turn_off
    entity_id: group.tuinverlichting
#
# Regenachtige dag
#
- id: '11'
  alias: '[Rainy] - Regenachtige dag monitor'
  initial_state: true
  trigger:
  - below: 120
    entity_id: sensor.gemiddeld_lichtniveau
    platform: numeric_state
  - above: 190
    entity_id: sensor.gemiddeld_lichtniveau
    platform: numeric_state
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    - condition: state
      entity_id: timer.regenachtigedag
      state: idle
    - condition: state
      entity_id: group.familie
      state: home
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.br_condition
        state: rainy
      - condition: state
        entity_id: sensor.br_condition
        state: snowy
  action:
  - data:
      entity_id: timer.regenachtigedag
    service: timer.start
  - entity_id: input_boolean.regenachtigedag
    service_template: >
      {% if states('sensor.gemiddeld_lichtniveau')|int < 125 %}
        homeassistant.turn_on 
      {% else %} 
        homeassistant.turn_off 
      {% endif %}
# Verlichting uit bij regenachtige dag
- id: '12'
  alias: '[Rainy] - Regenachtige dag verlichting uit'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.regenachtigedag
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_off
    data:
      entity_id: 
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
# Verlichting aan bij regenachtige dag
- id: '13'
  alias: '[Rainy] - Regenachtige dag verlichting aan'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.regenachtigedag
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
  action:
  - service: light.turn_on
    data:
      entity_id:
      - light.woonkamer
      - light.keuken
  - service: homeassistant.turn_on
    data:
      entity_id: 
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
#
# Theming
#
# Dag licht theme
- id: '14'
  alias: '[Theme] - Light theme after Sunrise'
  trigger:
    platform: sun
    event: sunrise
  action:
    - service: frontend.set_theme
      data:
# Light theme bij start
        name: Google - Light
- id: '15'
  alias: '[Theme] - Dark theme after Sunset'
  trigger:
    platform: sun
    event: sunset
  action:
    - service: frontend.set_theme
      data:
# Dark theme bij start
        name: Google - Dark
- id: '16'
  alias: '[Theme] - Light theme after reboot in day'
  trigger:
    platform: homeassistant
    event: start
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    service: frontend.set_theme
    data:
# Light theme bij zonsopgang
      name: Google - Light
- id: '17'
  alias: '[Theme] - Dark theme after reboot in night'
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: frontend.set_theme
    data:
# Dark theme bij zonsondergang
      name: Google - Dark
- id: '18'
  alias: '[Motion] - Timer voor beweging in de woonkamer'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.aeotec_limited_zwa005_trisensor_sensor, binary_sensor.woonkamer_sensor_motion
    to: 'off'
  action:
  - service: timer.start
    data:
      entity_id: timer.woonkamer
#
# Deurbel
#
- id: '19'
  alias: '[Doorbell] - Verlichting knipperen bij aanbellen avond'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_ding
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: group.woonkamer
    state: 'on'
  action:
  - service: homeassistant.toggle
    entity_id:
    - group.woonkamer
  - delay: 00:00:01
  #- service: homeassistant.toggle
  #  entity_id:
  #  - group.woonkamer
  #- delay: 00:00:01
  #- service: homeassistant.toggle
  #  entity_id:
  #  - group.woonkamer
  #- delay: 00:00:01
  - service: homeassistant.toggle
    entity_id:
    - group.woonkamer
  - delay: 00:00:07
- id: '20'
  alias: '[Kitchen] - Dim keukenverlichting om 20u'
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: light.keuken
    state: 'on'
  action:
  - delay: >
      {{ "00:%02d:00" % (range(1, 5) | random) }}
  - service: light.turn_on
    data:
      entity_id:
      - light.keuken
      color_temp: 443
      brightness: 100
#
# Update notificatie
#
- id: '21'
  alias: '[Update] - Update Available Notification'
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
  - service: notify.hass_notification
    data_template:
      title: "Home Assistant Update Notificatie"
      message: >
        Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available.
      data:
        url: "https://www.home-assistant.io/latest-release-notes/"
      target: device/Gertjan
#
# Droger
#
# Zet de droger naar standby als de wasmachine klaar is
- id: '22'
  alias: '[Droger] - Zet droger standby als wasmachine klaar'
  trigger:
    - platform: state
      entity_id: sensor.wasmachine_washer_machine_state
      to: run
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Standby
# Als het gemiddelde stroomverbruik hoger dan 1800W is voor 30 minuten 
# markeer de droger als drogen
- id: '23'
  alias: '[Droger] - Zet droger naar drogen'
  trigger:
  - platform: numeric_state
    entity_id: sensor.statistics_on_power_consumption
    above: 1800
    for:
        minutes: 25
  condition:
    condition: or
    conditions:
      - condition:  state
        entity_id: input_select.droger_status
        state: Uit
      - condition:  state
        entity_id: input_select.droger_status
        state: Standby
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Drogen
# Als het gemiddelde stroomverbruik onder 1200W komt is de droger klaar
# Stuur een bericht dat de droger klaar is
- id: '24'
  alias: '[Droger] - Zet Droger naar klaar en stuur bericht'
  trigger:
    - platform: numeric_state
      entity_id: sensor.statistics_on_power_consumption
      below: 1200
      for:
        minutes: 10
  condition:
  - condition: state
    entity_id: input_select.droger_status
    state: Drogen
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Klaar
    - service: notify.hass_notification
      data_template:
        title: "Droger Status"
        message: "De droger is klaar."
        target:
        - device/Gertjan
        - device/Lisette
# Als de droger 5 minuten klaar is of als de droger langer dan 6 uur op
# standby staat zet hem dan naar uit.
- id: '25'
  alias: '[Droger] - Zet droger uit'
  trigger:
    - platform: state
      entity_id: input_select.droger_status
      to: Klaar
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.droger_status
      to: standby
      for:
        hours: 6
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.droger_status
        option: Uit
#
# Screens
#
# Naar beneden, buiten koud en familie thuis
- id: '26'
  alias: '[Screens] - Screens naar beneden bij koud weer'
  trigger:
    - platform: numeric_state
      entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
      above: 32000
      for:
        minutes: 3
    - platform: state
      entity_id: group.familie
      from: "not_home"
      to: "home"
      for:
        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.maintenance_mode
        state: 'off'
      - condition: state
        entity_id: group.familie
        state: home
      - condition: numeric_state
        entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
        above: 31000
      - condition: numeric_state
        entity_id: sensor.zon_azimuth
        above: 170
      - condition: numeric_state
        entity_id: sensor.zon_azimuth
        below: 260
      - condition: numeric_state
        entity_id: sensor.br_temperature
        below: 16
      - condition: numeric_state
        entity_id:  sensor.br_wind_force
        below: 7
      #- condition: template
      #  value_template: >
      #    {{ states('sensor.br_condition') in ['clear', 'partlycloudy'] }}
      - condition: or
        conditions:
        - condition: template
          value_template: >
            {{ (state_attr('cover.grote_raam', 'current_position') | int) == 100 }}
        - condition: template
          value_template: >
            {{ (state_attr('cover.keukenraam', 'current_position') | int) == 100 }}
  action:
    - service: cover.set_cover_position
      entity_id: group.alle_screens
      data_template:
        position: 40
# Naar beneden, buiten warm
- id: '27'
  alias: '[Screens] - Screens naar beneden bij warm weer'
  trigger:
    - platform: numeric_state
      entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
      above: 28000
      for:
        minutes: 3
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.maintenance_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.br_temperature
        above: 16
      - condition: numeric_state
        entity_id: sensor.br_wind_force
        below: 7
      - condition: numeric_state
        entity_id: sensor.zon_azimuth
        below: 270
      #- condition: template
      #  value_template: >
      #    {{ states('sensor.br_condition') in ['clear', 'partlycloudy'] }}
      - condition: or
        conditions:
        - condition: template
          value_template: >
            {{ (state_attr('cover.grote_raam', 'current_position') | int) == 100 }}
        - condition: template
          value_template: >
            {{ (state_attr('cover.keukenraam', 'current_position') | int) == 100 }}
  action:
    - service: cover.close_cover
      entity_id: group.alle_screens
# Naar boven
- id: '28'
  alias: '[Screens] - Screens naar boven'
  trigger:
    - platform: numeric_state
      entity_id: sensor.hue_outdoor_motion_sensor_1_light_level
      below: 20000
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: sensor.br_wind_force
      above: 7
    - platform: numeric_state
      entity_id: sensor.zon_azimuth
      above: 280
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: >
          {{ (state_attr('cover.grote_raam', 'current_position') | int) != 100 }}
      - condition: template
        value_template: >
          {{ (state_attr('cover.keukenraam', 'current_position') | int) != 100 }}
  action:
    - service: cover.open_cover
      entity_id: group.alle_screens