homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: -5 
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  auth_providers:
    - type: homeassistant
    # Uncomment next line if you want to enable legacy API password support
    #- type: legacy_api_password
  # Include the packages directory and all content in it
  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml
  # whitelisted external storage directories
  allowlist_external_dirs: 
    - /tmp
  # Internal and External URL's
  external_url: !secret external_url
  internal_url: !secret internal_url

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  #themes: !include themes.yaml
  themes: !include_dir_merge_named themes
  javascript_version: latest

# System logging to trigger automations
system_log:
  fire_event: true

# Recording of states of the last 2 days only
recorder:
  purge_keep_days: 7
  auto_purge: true

# History only shows the following domains and entities
history:
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - media_player
      - camera
      - climate
    entities:
      - device_tracker.oneplus3t
      - device_tracker.oneplus_a3003
      - device_tracker.android77ac869bd554e5b7
      - device_tracker.iphone_2
      - device_tracker.galaxys9
      - zwave.nig1
      - zwave.nig2
      - zwave.nig3
      - zwave.nig4
      - zwave.nig5
      - zwave.nig6
      - zwave.nig7
      - zwave.nig8
      - zwave.nig9
  exclude:
    entities:
    - binary_sensor.updater
    - sensor.installed_version
    - sensor.moon
    - sensor.br_stationname
    - sensor.br_condition_code
    - sensor.br_condition
    - sensor.br_detailed_condition
    - sensor.br_full_condition
    - sensor.br_symbol
    - sensor.br_humidity
    - sensor.br_temperature
    - sensor.br_ground_temperature
    - sensor.br_wind_speed
    - sensor.br_wind_force
    - sensor.br_wind_direction
    - sensor.br_wind_direction_azimuth
    - sensor.br_pressure
    - sensor.br_visibility
    - sensor.br_wind_gust
    - sensor.br_precipitation
    - sensor.br_irradiance
    - sensor.br_precipitation_forecast_average
    - sensor.br_precipitation_forecast_total
    - sensor.br_symbol_1d
    - sensor.br_symbol_2d
    - sensor.br_symbol_3d
    - sensor.br_symbol_4d
    - sensor.br_symbol_5d
    - sensor.br_temperature_1d
    - sensor.br_temperature_2d
    - sensor.br_temperature_3d
    - sensor.br_temperature_4d
    - sensor.br_temperature_5d
    - sensor.br_mintemp_1d
    - sensor.br_mintemp_2d
    - sensor.br_mintemp_3d
    - sensor.br_mintemp_4d
    - sensor.br_mintemp_5d
    - sensor.br_rainchance_1d
    - sensor.br_rainchance_2d
    - sensor.br_rainchance_3d
    - sensor.br_rainchance_4d
    - sensor.br_rainchance_5d
    - sensor.br_sunchance_1d
    - sensor.br_sunchance_2d
    - sensor.br_sunchance_3d
    - sensor.br_sunchance_4d
    - sensor.br_sunchance_5d
    - sensor.br_rain_1d
    - sensor.br_rain_2d
    - sensor.br_rain_3d
    - sensor.br_rain_4d
    - sensor.br_rain_5d
    - sensor.time
    - sensor.date
    - sensor.date_time
    - sensor.date_time_iso
    - sensor.time_date
    - sensor.time_utc
    - sensor.internet_time
    - sensor.zonnestand
    - sensor.zon_azimuth
    - sensor.bewegingsdetectie_woonkamer
    - sensor.dark_sky_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_daily_low_temperature_1d
    - sensor.bewegingsdetectie_buiten
    - sensor.dark_sky_daily_high_temperature_1d
    - sensor.buiten_hue_light_level
    - sensor.dark_sky_humidity
    - sensor.dark_sky_humidity_1d
    - sensor.dark_sky_precip_probability
    - sensor.dark_sky_precip_probability_1d
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_precip_intensity_1d
    - sensor.dark_sky_precip
    - sensor.dark_sky_precip_1d
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_wind_speed_1d
    - sensor.dark_sky_wind_bearing
    - sensor.dark_sky_wind_bearing_1d
    - sensor.dark_sky_pressure
    - sensor.dark_sky_pressure_1d
    - sensor.dark_sky_icon
    - sensor.dark_sky_icon_1d
    - sensor.dark_sky_summary
    - sensor.dark_sky_summary_1d
    - sensor.latest_available_version
    - sensor.dark_sky_minutely_summary
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_summary
    - sun.sun
    - timer.woonkamer
    - timer.regenachtigedag

# Logging of information, no need for anything below warn level
logger:
  default: warn

# influxdb

influxdb:
  host: 127.0.0.1
  max_retries: 3
  default_measurement: state
  component_config_domain:
    climate:
      override_measurement: temperature
  component_config_glob:
    sensor.*humidity:
      override_measurement: humidity
    sensor.*temperature:
      override_measurement: temperature
    sensor.rain_*:
      override_measurement: mm

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/atomic_calendar/atomic_calendar.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/banner-card/banner-card.js
      type: module
    - url: /local/simple-clock-card.js
      type: js
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: js
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: js
    - url: /hacsfiles/lovelace-gap-card/gap-card.js
      type: js
    - url: /local/custom-lovelace/graph-card/graph-card.js?v=0.1
      type: js
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: module
    - url: /hacsfiles/dual-gauge-card/dual-gauge-card.js
      type: js
  dashboards:
    tablet-dash: # Needs to contain a hyphen (-)
      mode: yaml
      filename: tablet.yaml
      title: Tablet
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
    mobile-dash:
      mode: yaml
      title: Mobile
      icon: mdi:android
      show_in_sidebar: true
      filename: mobile.yaml
# Home Assistant Community Store
hacs:
  token: !secret my_github_access_token

# MDI icon index panel
#panel_iframe:
#  mdiindex:
#    title: MDI Icon Index
#    icon: mdi:vector-square
#    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

python_script:

# Show the introduction message on startup.
#introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  # Deprecated since 0.90 
  #api_password: !secret http_password
  # end
  #base_url: !secret duckdns_url
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key

# Let's Encrypt certificate expiry
#sensor:
#  - platform: cert_expiry
#    host: !secret duckdns_url

# Sensors
# Track the sun
sun:

# Weather prediction
weather:
  - platform: buienradar
    name: 'schiphol'
    forecast: True

# Text to speech
#tts:
#  - platform: google_translate
#    service_name: google_say
    
# Z-wave controller
zwave:
  usb_path: /dev/ttyACM0
  #usb_path: /dev/ttyACM1
  network_key: !secret zwave_network_key
  polling_interval: 60000 

# Verwarming
evohome:
  username: !secret honeywell_username
  password: !secret honeywell_password

# Disabled yaml configuration due to 2FA requirement
# Deurbel
#ring:
#  username: !secret ring_username
#  password: !secret ring_password

# Sunscreens
somfy:
  client_id: !secret somfy_key
  client_secret: !secret somfy_secret

# Pushbullet notification service
notify:
  - name: hass_notification
    platform: pushbullet
    api_key: !secret pushbullet_key
  - platform: group
    name: gertjan_push
    services:
      - service: hass_notification
        data:
          target: device/GertjanOP3T

# If This Then That
#ifttt:

# FFmpeg is a complete, cross-platform solution to record, convert and stream audio and video. 
# It includes libavcodec - the leading audio/video codec library.
ffmpeg:

# Z-Wave network panel	
panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

# modem for presence detector
device_tracker:
  - platform: fritz
    interval_seconds: 60
    consider_home: 300
    new_device_defaults:
      track_new_devices: True
      #hide_if_away: False

# Google Maps Location Sharing
#  - platform: google_maps
#    username: !secret google_username
#    password: !secret google_password
#    max_gps_accuracy: 500

# Google api for google calendar
# https://console.developers.google.com/start/api?id=calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Foscam en Ring cameras
camera:
  - platform: foscam
    name: !secret camera_a_name
    ip: !secret camera_a_ip
    username: !secret camera_username
    password: !secret camera_password
  - platform: foscam
    name: !secret camera_e_name
    ip: !secret camera_e_ip
    username: !secret camera_username
    password: !secret camera_password
#  - platform: ring

# MQTT broker
mqtt:
#   broker: localhost
   broker: !secret mqtt_broker_ip
#   username: mqtt_user
#   password: !secret mqtt_password
   client_id: hass
   birth_message:
     topic: 'hass/status'
     payload: 'online'
     qos: 1
     retain: true
   will_message:
     topic: 'hass/status'
     payload: 'offline'
     qos: 1
     retain: true

# timers
timer:
  woonkamer:
    duration: '00:10:00'
  regenachtigedag:
    duration: '00:30:00'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
zone: !include zones.yaml
binary_sensor: !include binary_sensors.yaml
input_datetime: !include input_datetime.yaml